Assignment1-added updated
rianrishu/Nuclei-Assignment pull request #2
Opened 2023-01-25 06:25 UTC by rianrishu

2023-01-27 07:30 UTC, PrashantKumarR requested changes
Please review the comments and make change. If you have any doubt try to learn by googling or ask me in chat.

2023-01-27 07:30 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Item.java
> +            double surcharge = 0;
Keep declaration and initialisation together if possible -             double importDuty =  0.10 * this.price;

2023-01-27 07:30 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Item.java
> +            double temp = tax + importDuty + this.price;
Always give meaningful name to variables - "temp", "a", "b" etc are not meaningful variable names.

2023-01-27 07:30 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Item.java
> +            }
Since these conditions are exclusive of each other, you can use else-if construct here and also see if the same result can be achieved by using lesser condition.

2023-01-27 07:30 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Item.java
> +    void calculateTotal(){
Write this method to return value so that you can test it easily.

2023-01-27 07:30 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Part.java
> +            Item[] items = new Item[1000];
See if using List will make it easier to handle the data.

2023-01-27 07:30 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Part.java
> +            char cont = 'y';
Rename the variable to more meaningful one.

2023-01-27 07:30 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Part.java
> +                } catch(InputMismatchException e){
Handle the exception at the point of input so that user gets an opportunity to input correct value.

2023-01-27 07:30 UTC, PrashantKumarR commented on src/test/java/org/example/assignment1/ItemTest.java
> +class ItemTest {
Your unit test should include test for calculate total also.

2023-01-30 06:02 UTC, rianrishu commented on src/main/java/org/example/assignment1/Item.java
> +        return Math.round(tax * 1000) / 1000.0;
if price = 190, => tax = 23.75
importduty = 19,
addTaxImportPrice = 190 + 23.75 + 19 = 232.75,
sucharge = 0.05 * 232.75 = 11.6375,
final tax = 232.75 + 11.6375 - 190 = 54.3875,
which round off to 54.387

2023-01-30 06:10 UTC, PrashantKumarR requested changes

2023-01-30 06:10 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Part.java
> +                    System.out.println("1.Raw\n2.Manufactured\n3.Imported\n");
User should be able to understand that they have to input options 1,2 or 3 and not type the text.

2023-01-30 06:10 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Part.java
> +            } while(addMore == 'y');
Allow user to enter in upper case also.

2023-02-13 02:12 UTC, PrashantKumarR requested changes

2023-02-13 02:12 UTC, PrashantKumarR commented on src/main/java/org/example/assignment1/Part.java
> +                    type = ItemType.imported;
what if user enters 4?

2023-02-14 02:38 UTC, PrashantKumarR approved these changes

2023-02-14 03:00 UTC, merged

2023-02-14 13:13 UTC, ashank96 commented on src/main/java/org/example/assignment1/Item.java
> +    double calculateTax() {
what if more item types are added to the system. Will you add more switch cases ?

Use Factory design pattern. [Read more ](https://www.digitalocean.com/community/tutorials/factory-design-pattern-in-java)

2023-02-14 13:17 UTC, ashank96 commented on src/main/java/org/example/assignment1/Part.java
> +                items.add(new Item(name, price, quantity, type));
when you use factory pattern, then no need to store type as an attribute of Item class.